language: node_js
sudo: false
node_js:
  - 8
  - 10
  - 11
os:
  - windows
  - linux
  - osx
addons:
    firefox: latest
    chrome: stable
install:
  - npm install --global yarn lerna
  - lerna bootstrap
  - lerna exec -- yarn link
script:
    - npm test -- --verbose
cache: yarn
